baseurl: /et2021uiuc
sass:
  sass_dir: _sass
incremental: true
collections:
  lectures:
    output: true
# Jekyll 4 supports an order attribute here, Jekyll 3 relies on file names
# only. Github (2021-04-20) uses 3.9. See: https://pages.github.com/versions/
#   order:
#     - 00-AlbertEinsteint/index.d
